// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJewi9S3ybL9R4oTS4cHTph1TtZCVkhkg',
    appId: '1:376485033348:web:23f8183374ab47b26a99d1',
    messagingSenderId: '376485033348',
    projectId: 'pizzaapp-aa8c5',
    authDomain: 'pizzaapp-aa8c5.firebaseapp.com',
    storageBucket: 'pizzaapp-aa8c5.appspot.com',
    measurementId: 'G-ZZ10W50XJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMDunpi_9B7idWnOkmpyhtwkKoosGJfjM',
    appId: '1:376485033348:android:7d965778b7cf14256a99d1',
    messagingSenderId: '376485033348',
    projectId: 'pizzaapp-aa8c5',
    storageBucket: 'pizzaapp-aa8c5.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJewi9S3ybL9R4oTS4cHTph1TtZCVkhkg',
    appId: '1:376485033348:web:62d6bd8e869dcb976a99d1',
    messagingSenderId: '376485033348',
    projectId: 'pizzaapp-aa8c5',
    authDomain: 'pizzaapp-aa8c5.firebaseapp.com',
    storageBucket: 'pizzaapp-aa8c5.appspot.com',
    measurementId: 'G-S89ZQ2Q84R',
  );
}
