// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:
        'AIzaSyBJewi9S3ybL9R4oTS4cHTph1TtZCVkhkgBJewi9S3ybL9R4oTS4cHTph1TtZCVkhkg',
    appId: '1:376485033348:web:bb6c02624b0c055b6a99d1',
    messagingSenderId: '376485033348',
    projectId: 'pizzaapp-aa8c5',
    authDomain: 'pizzaapp-aa8c5.firebaseapp.com',
    storageBucket: 'pizzaapp-aa8c5.appspot.com',
    measurementId: 'G-6G3GHKL44F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'AIzaSyBJewi9S3ybL9R4oTS4cHTph1TtZCVkhkgCf12UCmHTL3Uv_u-AM71y_ckPjXQMVIUU',
    appId: '1:955012433071:android:960e1e247d1d384c1bc05a',
    messagingSenderId: '955012433071',
    projectId: 'pizzaapp-aa8c5',
    storageBucket: 'pizzaapp-aa8c5.appspot.com',
  );
}
